##################################
# Constants shared across modules#
##################################

PTT_DELAY_TIME = const(250) # Time delay between PTT and mute
KNOB_LONG_PRESS_TIME = const(1000) # Time for knob to be held down to register a long press
TX_TIME_OUT_TIME = const(600000) # 10 minute TOT
GC_COLLECT_INTERVAL = const(30000) # 30 seconds


# Transmit states used by display and vfo
TXS_RX = 0
TXS_TX = 1
TXS_TUNE = 2
TXS_TIMEOUT = 3

# Emission modes
TXM_LSB = 0
TXM_USB = 1


# Event types
ET_ALL = const(0xFFFFFFFF)
ET_ENCODER = const(0x00000001)
ET_SWITCHES = const(0x00000002)
ET_VFO = const(0x00000004)
ET_DISPLAY = const(0x00000008)


# Event subtypes
EST_NONE = 0
EST_KNOB_CW = 1
EST_KNOB_CCW = 2
EST_KNOB_MENU_CW = 3
EST_KNOB_MENU_CCW = 4
EST_KNOB_PRESSED = 5
EST_KNOB_RELEASED = 6
EST_KNOB_RELEASED_LONG = 7
EST_TUNE_PRESSED = 8
EST_TUNE_RELEASED = 9
EST_PTT_PRESSED = 10
EST_PTT_RELEASED = 11
EST_TX_TIMED_OUT_ENTRY = 12
EST_TX_TIMED_OUT_EXIT = 13
EST_DISPLAY_UPDATE_FREQ = 14
EST_DISPLAY_UPDATE_MODE = 15
EST_DISPLAY_UPDATE_TXSTATE = 16
EST_DISPLAY_UPDATE_TUNING_INCR = 17
EST_DISPLAY_UPDATE_AGC = 18
EST_VFO_AGC_DISABLE = 19
EST_VFO_AGC_ENABLE = 20
EST_VFO_MODE_LSB = 21
EST_VFO_MODE_USB = 22
EST_DISPLAY_MENU_ENTRY = 23
EST_DISPLAY_MENU_EXIT = 24
EST_DISPLAY_MENU_UPDATE = 25

EST_DISPLAY_FATAL_ERROR = const(911)


